bug fix

diff --git a/hello_world/2-assembler b/hello_world/2-assembler
--- a/hello_world/2-assembler
+++ b/hello_world/2-assembler
@@ -1,2 +1,13 @@
 #!/bin/bash
-gcc -s "$CFILE" -o "${CFILE%.c}.s"
+# C name
+# error handling
+if [ -z "$CFILE" ]; then
+    echo "Error: CFILE is not set"
+    exit 1
+fi
+
+# .c reverse .s
+output_file="${CFILE%.c}.s"
+
+# gcc ile assembly ceated
+gcc -S "$CFILE" -o "$output_file"
